INSERT INTO characters(name, img)
    VALUES
        ('Mario','mario.jpg'),
        ('Donkey Kong','donkey-kong.jpg'),
        ('Link','link.jpg'),
        ('Samus','samus.jpg'),
        ('Dark Samus','dark-samus.jpg'),
        ('Yoshi','yoshi.jpg'),
        ('Kirby','kirby.jpg'),
        ('Fox','fox.jpg'),
        ('Pikachu','pikachu.jpg'),
        ('Luigi','luigi.jpg'),
        ('Ness','ness.jpg'),
        ('Captain Falcon','captain-falcon.jpg'),
        ('Jigglypuff','jigglypuff.jpg'),
        ('Peach','peach.jpg'),
        ('Daisy','daisy.jpg'),
        ('Bowser','bowser.jpg'),
        ('Ice Climbers','ice-climbers.jpg'),
        ('Sheik','sheik.jpg'),
        ('Zelda','zelda.jpg'),
        ('Dr Mario','dr-mario.jpg'),
        ('Pichu','pichu.jpg'),
        ('Falco','falco.jpg'),
        ('Marth','marth.jpg'),
        ('Lucina','lucina.jpg'),
        ('Young Link','young-link.jpg'),
        ('Ganondorf','ganondorf.jpg'),
        ('Mewtwo','mewtwo.jpg'),
        ('Roy','roy.jpg'),
        ('Chrom','chrom.jpg'),
        ('Mr Game & Watch','mr-game-and-watch.jpg'),
        ('Meta Knight','meta-knight.jpg'),
        ('Pit','pit.jpg'),
        ('Dark Pit','dark-pit.jpg'),
        ('Zero Suit Samus','zero-suit-samus.jpg'),
        ('Wario','wario.jpg'),
        ('Snake','snake.jpg'),
        ('Ike','ike.jpg'),
        ('Pokemon Trainer','pokemon-trainer.jpg'),
        ('Diddy Kong','diddy-kong.jpg'),
        ('Lucas','lucas.jpg'),
        ('Sonic','sonic.jpg'),
        ('King Dedede','king-dedede.jpg'),
        ('Olimar','olimar.jpg'),
        ('Lucario','lucario.jpg'),
        ('Rob','rob.jpg'),
        ('Toon Link','toon-link.jpg'),
        ('Wolf','wolf.jpg'),
        ('Villager','villager.jpg'),
        ('Mega Man','mega-man.jpg'),
        ('Wii Fit Trainer','wii-fit-trainer.jpg'),
        ('Rosalina and Luma','rosalina-and-luma.jpg'),
        ('Little Mac','little-mac.jpg'),
        ('Greninja','greninja.jpg'),
        ('Palutena','palutena.jpg'),
        ('Pac Man','pac-man.jpg'),
        ('Robin','robin.jpg'),
        ('Shulk','shulk.jpg'),
        ('Bowser Jr','bowser-jr.jpg'),
        ('Duck Hunt','duck-hunt.jpg'),
        ('Ryu','ryu.jpg'),
        ('Ken','ken.jpg'),
        ('Cloud','cloud.jpg'),
        ('Corrin','corrin.jpg'),
        ('Bayonetta','bayonetta.jpg'),
        ('Inkling','inkling.jpg'),
        ('Ridley','ridley.jpg'),
        ('Simon','simon.jpg'),
        ('Richter','richter.jpg'),
        ('King K Rool','king-k-rool.jpg'),
        ('Isabelle','isabelle.jpg'),
        ('Incineroar','incineroar.jpg'),
        ('Piranha Plant','piranha-plant.jpg'),
        ('Joker','joker.jpg'),
        ('Mii Brawler','mii-brawler.jpg'),
        ('Mii Swordsman','mii-swordsman.jpg'),
        ('Mii Gunner','mii-gunner.jpg')
    ;